sudo: required
services:
  - docker

before_install:
  - docker build -t cristhiandsz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cristhiandsz/react-test npm test

after_success:
  - docker build -t cristhiandsz/multi-client ./client
  - docker build -t cristhiandsz/multi-nginx ./nginx
  - docker build -t cristhiandsz/multi-server ./server
  - docker build -t cristhiandsz/multi-worker ./worker
  # Login into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Push those images to docker hub
  - docker push cristhiandsz/multi-client
  - docker push cristhiandsz/multi-nginx
  - docker push cristhiandsz/multi-server
  - docker push cristhiandsz/multi-worker
